### ISSUE TITLE
Squeel breaks marshalling of ActiveRecord models with loaded association objects

### ISSUE THREAD

**Issue by jhuckabee** [activerecord-hackery/squeel#232]
This can be reproduced via the following:

``` ruby
class List < ActiveRecord::Base
  has_many :list_items
end

class ListItem < ActiveRecord::Base
  belongs_to :list
end

list = List.create(name: 'List 1')
list.list_items << ListItem.new(name: 'List Item 1')
list.list_items << ListItem.new(name: 'List Item 2')

list = List.find(1)
Marshal.dump(list) # This works with or without Squeel
list.list_items
Marshal.dump(list) # This fails when Squeel is added to the mix with:
                   # TypeError: can't dump hash with default proc
```

A quick grep of the code yields 4 instances of Hash instantiations with default procs. Is it possible to work around these?

**Comment by frunns** [comment]
Thanks for the monkey patch! As @workmaster2n says, it'd be nice to know what the effects are. For me the error is only present in development, in production it works just fine.

**Comment by bunyan** [comment]
The bug is still present with Rails 4.2.3 and Squeel 1.2.3, and the patch is still working. Thanks @elado!

**Comment by letronje** [comment]
Yup, I can confirm this. Seeing this with rails 4.2.4 and squeel 1.2.3. The monkey patch works. Please consider including this patch into squeel.

**Comment by shepmaster** [comment]
Continuing to see this with Rails 4.2.5.1 and Squeel 1.2.3. The monkeypatch also seemed to help me.

What was tricky, as @elado points out, is that the error message isn't easily connected to Squeel in any way. You don't even need to be using any Squeel functionality on the models being cached; just having Squeel loaded is enough.

If I hadn't already had caching in the app and then added Squeel, it would be very difficult to find this issue.
