### ISSUE TITLE
Conditions within a join

### ISSUE THREAD

**Issue by nottombrown** [activerecord-hackery/squeel#283]
I would love it if there was syntax to add constraints to the join conditions (before the join occurs)

For example if we want all the members without an active blocker

```
  LEFT JOIN blockers
  ON blockers.member_id = members.id AND blockers.state = 'active' 
  WHERE blockers.id IS NULL
```

Would you accept a pull request that adds the following syntax?

```
  joins{ blockers.where(:state => 'active') }.
    where(blockers => {:id => nil})
```

**Comment by agrass** [comment]
Thanks @bigxiang, but what happens if you don't know from the beginning which type of scope I'm going to do? For example if I have dynamic types of metadata in same table that means different things.
