### ISSUE TITLE
Feature request: filtering with predicates using params hash

### ISSUE THREAD

**Issue by bostrom** [activerecord-hackery/squeel#370]
It would be very nice to be able to build up a filter including predicates in the front-end using javascript object notation and have it passed straight into Squeel for evaluation. 

Squeel already does 

```ruby
Person.where{(name =~ 'Ernie%') & (salary < 50000) | (name =~ 'Joe%') & (salary > 100000)}
```
but if the query comes from a detached front end (e.g. over a REST API), it would be convenient to be able to pass the predicate to squeel directly from the query params, like so:

```javascript
var filter = {
  filter: {
    or: [{
      and: [
        { name: { like: 'Ernie%' } },
        { salary: { lt: 50000 } }
      ]
    }, {
      and: [
        { name: { like: 'Joe%' } },
        { salary: { lt: 100000 } }
      ]
    }]
  }
};
$.ajax('http://localhost:3000/api/users', {
  method: 'GET',
  data: $.param(filter)
});

// /api/users?filter[or][0][and][0][name][like]=Ernie%&filter[or][0][and][1][salary][lt]=50000&filter[or][1][and][0][name][like]=Joe%&filter[or][1][and][1][salary][lt]=100000
```
Now ```params[:filter]``` would contain the corresponding hash as the javascript object above and it would be damn convenient if one could pass that straight into ```User.where{}```.

I've looked around for a gem that would implement this sort of functionality, but haven't found one. Squeel seems to be a good candidate for this sort of thinking, though. Does this sound like something the Squeel philosophy could relate to?

**Comment by vendethiel** [comment]
Looks like something ransack could be useful for

**Comment by bostrom** [comment]
Ah yes, so it seems. At least that would be a more suitable project for implementing this kind of thing. Thanks.
