### ISSUE TITLE
Undefined method | (pipe)

### ISSUE THREAD

**Issue by andyrue** [activerecord-hackery/squeel#406]
I'm in the process of upgrading my rails app from 3.2 to 4.1.13 and I'm running into an issue with one of my scopes.

    scope :for_current_or_last_year, lambda {
       where({:year_id => Year.current.id} | {:year_id => Year.ago(1).id}) }

This used to work, but now it complains about the `|` OR operator. undefined method `|' for {:year_id=>9}:Hash

This is the SQL that is generated.
    SELECT `approvals`.* FROM `approvals`  WHERE ((`approvals`.`year_id` = 9 OR `approvals`.`year_id` = 8))

I haven't been able to get the same SQL query with any of my rewrites, just ones that sort of work but don't give the same results when I use that scope to join some other queries.

Any idea how I can get it going again? Squeel is currently version 1.2.3, and was 0.9.5 before the upgrade. Thanks for your help!

**Comment by andyrue** [comment]
Ok, I found out I need to initialize core extensions for hashes. I had disabled them due to the deprecation warning about it going away in version 2.0. What's the proper way to do that for Squeel 2.0?

**Comment by ernie** [comment]
Squeel 2.0 is/was pretty much all about the DSL blocks. In there, you'd specify the equality conditions separately using the DSL and use the pipe between them with no issues.
