### ISSUE TITLE
Group_by not working 

### ISSUE THREAD

**Issue by Jrsnow8921** [activerecord-hackery/squeel#410]
I have this active record query using squeel, I also need to group them by either leave_start.to_date or leave_end.to_date. For some reason this isn't working any help would be greatly appreciated. 

```
  entry_by_start_date = Entry.where{(emp_dept.like any t) & (auth == 'E') & (approve_disapprove.like_any a_d)}.group_by {|i| i.leave_start.to_date}
  entry_by_end_date = Entry.where{(emp_dept.like any t) & (auth == 'E') & (approve_disapprove.like_any a_d)}.group_by {|i| i.leave_end.to_date}
```

It seems like its not tacking on the group_by ....
Here is the error --->>>> 
ActiveRecord::StatementInvalid (OCIError: ORA-00936: missing expression: SELECT "TO_ENTRIES".\* FROM "TO_ENTRIES" WHERE ("TO_ENTRIES"."EMP_DEPT" LIKE any('PLTDUP', 'PLTINS') AND "TO_ENTRIES"."AUTH" = 'E' AND ("TO_ENTRIES"."APPROVE_DISAPPROVE" LIKE '1' OR "TO_ENTRIES"."APPROVE_DISAPPROVE" LIKE '2'))): app/controllers/entry_controller.rb:115:in `index'

**Comment by chewi** [comment]
This doesn't make sense. `group_by` is an Array method in Ruby, which isn't the same as the `group` method in ActiveRecord for performing a SQL `GROUP BY`.
